name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t reqres-api-testing-framework .

      - name: Run tests inside Docker container
        run: |
          docker run --rm \
            -e API_KEY=${{ secrets.API_KEY }} \
            -v "${{ github.workspace }}/allure-results:/app/allure-results" \
            reqres-api-testing-framework \
            pytest --alluredir=allure-results

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
